#!/bin/bash

network=mainnet

if [ "$1" '!=' "admin" ];
then
	echo 'Only admins are allowed to access Thunderhub' >&2
	exit 1
fi

token="`cat "/var/run/thunderhub-system-$network/sso/cookie"`" || exit 2
echo -n "?token=$token"
